
-- Generated by ORDS REST Data Services 25.4.0.r3641739
-- Schema: WKSP_PAYSOFF  Date: Fri Jan 30 02:25:27 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'pays_off',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'test.app',
      p_base_path      => '/test/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'test.app',
      p_pattern        => 'monitoreo/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'test.app',
      p_pattern        => 'monitoreo/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_res pkg_voto_inteligente.t_reporte;
  v_primero BOOLEAN := TRUE;
BEGIN
  -- Cabeceras para que el navegador sepa que es un JSON
  owa_util.mime_header(''application/json'', FALSE);
  owa_util.http_header_close;
  
  sys.htp.p(''{"items": ['');
  
  -- Este bucle recorre los 18 departamentos que insertaste en la tabla
  FOR d IN (SELECT id_depto, nombre_depto FROM departamentos ORDER BY id_depto) LOOP
    
    -- Si no es el primer registro, ponemos una coma para separar los objetos JSON
    IF NOT v_primero THEN 
        sys.htp.p('',''); 
    END IF;
    
    -- Llamamos a tu paquete modular para procesar el departamento actual
    v_res := pkg_voto_inteligente.obtener_analisis_completo(d.id_depto);
    
    -- Imprimimos los datos procesados por el PKG
    sys.htp.p(''{"id": ''|| d.id_depto ||
            '', "departamento": "''|| d.nombre_depto ||
            ''", "promedio": ''|| NVL(v_res.promedio, 0) ||
            '', "estatus": "''|| NVL(v_res.estatus, ''SIN DATOS'') ||''"}'');
     ' || '       
    v_primero := FALSE;
  END LOOP;
  
  sys.htp.p('']}'');
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'test.app',
      p_pattern        => 'monitoreo/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    -- Actualizamos ''promedio'' para que el JSON de la web cambie a la vista
    UPDATE votaciones 
    SET promedio = :p_cantidad; 

    -- También actualizamos cantidad_personas para que los datos coincidan
    UPDATE votaciones 
    SET cantidad_personas = :p_cantidad;

    COMMIT; -- ¡Sin esto, Oracle no guarda el cambio permanentemente!
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'test.app',
      p_pattern        => 'resultados/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'test.app',
      p_pattern        => 'resultados/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT 
    id_voto, 
    cantidad_personas,
    ''Dato procesado por PKG'' as origen
FROM votaciones');


COMMIT;

END;